name-generator-api/config/routes.rb
Rails.application.routes.draw do
  resources :names

  namespace 'api' do
    resources :names, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

name-generator-api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

name-generator-api/app/models/name.rb
class Name < ApplicationRecord
  scope :roman_letter_like, lambda { |initial| where("roman_letter like :initial", initial: initial + '%') }
  extend Enumerize

  enumerize :sex, in: [:male, :female], scope: true

  def self.choose_name(original_name, birth_date, sex)
    row_num = (birth_date.year + birth_date.month + birth_date.day)

    if with_sex(sex).roman_letter_like(original_name[0..1]).present?
      candidates = with_sex(sex).roman_letter_like(original_name[0..1])
      logger.debug "プライオリティ1"
      return candidates[row_num % candidates.count]
    end

    if with_sex(sex).roman_letter_like(original_name[0]).present?
      logger.debug "プライオリティ2"
      candidates = with_sex(sex).roman_letter_like(original_name[0])
      return candidates[row_num % candidates.count]
    end

    candidates = with_sex(sex)
    logger.debug "プライオリティ3"
    candidate[row_num % candidates.count]
  end
end

name-generator-api/app/controllers/api/names_controller.rb
module Api
  class NamesController < ApplicationController
   
    def index
      @name = Name.choose_name(params[:name].downcase, params[:birth_date].to_date,params[:sex])
      render json: @name
    end

  end
end

name-generator-api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

name-generator-api/app/controllers/names_controller.rb
class NamesController < ApplicationController
  before_action :set_name, only: [:show, :edit, :update, :destroy]

  # GET /names
  # GET /names.json
  def index
    @names = Name.all
  end

  # GET /names/1
  # GET /names/1.json
  def show
  end

  # GET /names/new
  def new
    @name = Name.new
  end

  # GET /names/1/edit
  def edit
  end

  # POST /names
  # POST /names.json
  def create
    @name = Name.new(name_params)

    respond_to do |format|
      if @name.save
        format.html { redirect_to @name, notice: 'Name was successfully created.' }
        format.json { render :show, status: :created, location: @name }
      else
        format.html { render :new }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /names/1
  # PATCH/PUT /names/1.json
  def update
    respond_to do |format|
      if @name.update(name_params)
        format.html { redirect_to @name, notice: 'Name was successfully updated.' }
        format.json { render :show, status: :ok, location: @name }
      else
        format.html { render :edit }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /names/1
  # DELETE /names/1.json
  def destroy
    @name.destroy
    respond_to do |format|
      format.html { redirect_to names_url, notice: 'Name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_name
      @name = Name.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def name_params
      params.require(:name).permit(:roman_letter, :japanese, :sex)
    end
end

name-generator-api/app/helpers/application_helper.rb
module ApplicationHelper
end

name-generator-api/app/helpers/names_helper.rb
module NamesHelper
end

name-generator-api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NameGeneratorApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

name-generator-api/app/views/names/_form.html.erb
<%= form_with(model: name, local: true) do |form| %>
  <% if name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(name.errors.count, "error") %> prohibited this name from being saved:</h2>

      <ul>
      <% name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :roman_letter %>
    <%= form.text_field :roman_letter %>
  </div>

  <div class="field">
    <%= form.label :japanese %>
    <%= form.text_field :japanese %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

name-generator-api/app/views/names/edit.html.erb
<h1>Editing Name</h1>

<%= render 'form', name: @name %>

<%= link_to 'Show', @name %> |
<%= link_to 'Back', names_path %>

name-generator-api/app/views/names/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Names</h1>

<table>
  <thead>
    <tr>
      <th>Roman letter</th>
      <th>Japanese</th>
      <th>Sex</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @names.each do |name| %>
      <tr>
        <td><%= name.roman_letter %></td>
        <td><%= name.japanese %></td>
        <td><%= name.sex %></td>
        <td><%= link_to 'Show', name %></td>
        <td><%= link_to 'Edit', edit_name_path(name) %></td>
        <td><%= link_to 'Destroy', name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Name', new_name_path %>

name-generator-api/app/views/names/new.html.erb
<h1>New Name</h1>

<%= render 'form', name: @name %>

<%= link_to 'Back', names_path %>

name-generator-api/app/views/names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Roman letter:</strong>
  <%= @name.roman_letter %>
</p>

<p>
  <strong>Japanese:</strong>
  <%= @name.japanese %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @name.sex %>
</p>

<%= link_to 'Edit', edit_name_path(@name) %> |
<%= link_to 'Back', names_path %>